name: nirva
channels:
  - conda-forge
  - defaults
dependencies:
  # Core conda packages (removed build strings for cross-platform compatibility)
  - python=3.12
  - pip
  - asyncpg=0.29.0
  - bzip2=1.0.8
  - ca-certificates
  - cyrus-sasl=2.1.28
  - expat=2.5.0
  - greenlet=3.1.1
  - iniconfig=1.1.1
  - krb5=1.20.1
  - libffi=3.4.4
  - ncurses=6.4
  - openldap=2.6.4
  - openssl=3.0.16
  - pluggy=1.5.0
  - psycopg2=2.9.10
  - pyhumps=3.8.0
  - pytest=8.3.4
  - readline=8.2
  - redis=3.5.3
  - setuptools
  - sqlite=3.41.2
  - tk=8.6.12
  - typing-extensions=4.12.2
  - wheel
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      # Core FastAPI dependencies (synchronized with requirements.txt)
      - fastapi==0.110.0
      - uvicorn[standard]==0.27.1
      - pydantic==2.10.3
      - sqlalchemy==2.0.41
      - alembic==1.16.2
      - redis==6.2.0
      - psycopg2-binary==2.9.10
      - loguru==0.7.2
      - python-jose[cryptography]==3.4.0
      - passlib[bcrypt]==1.7.4
      - python-multipart==0.0.20
      - requests==2.31.0
      
      # LangChain ecosystem
      - langchain==0.3.11
      - langchain-core==0.3.24
      - langchain-openai==0.2.12
      - langchain-community==0.3.11
      - langchain-text-splitters==0.3.2
      - langgraph==0.2.59
      - langgraph-checkpoint==2.0.8
      - langgraph-sdk==0.1.43
      - langserve==0.3.0
      - langsmith==0.2.3
      
      # AI/ML dependencies
      - azure-identity==1.23.0
      - azure-core==1.34.0
      - openai==1.57.2
      - tiktoken==0.8.0
      - faiss-cpu==1.8.0
      
      # Web and networking
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - anyio==4.3.0
      - starlette==0.36.3
      - httpx==0.27.0
      - httpcore==1.0.4
      - httptools==0.6.4
      - httpx-sse==0.4.0
      - h11==0.14.0
      - uvloop==0.21.0
      - watchfiles==1.1.0
      - websockets==15.0.1
      
      # Data processing
      - numpy==1.26.4
      - pandas==2.2.3
      - openpyxl==3.1.2
      
      # Serialization
      - orjson==3.10.12
      - pyyaml==6.0.1
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      
      # Security and authentication
      - cryptography==44.0.3
      - bcrypt==3.2.2
      - ecdsa==0.19.1
      - rsa==4.9.1
      - pyasn1==0.4.8
      - pyjwt==2.10.1
      - msal==1.32.3
      - msal-extensions==1.3.1
      
      # Utilities
      - attrs==23.2.0
      - click==8.1.7
      - tenacity==8.2.3
      - tqdm==4.66.2
      - six==1.16.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.1
      - tzdata==2024.1
      - packaging==23.2
      - platformdirs==4.2.2
      - pathspec==0.12.1
      
      # Network protocols
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - urllib3==2.2.1
      - idna==3.6
      - sniffio==1.3.1
      - requests-toolbelt==1.0.0
      - multidict==6.0.5
      - yarl==1.9.4
      - frozenlist==1.4.1
      
      # Type system
      - annotated-types==0.6.0
      - pydantic-core==2.27.1
      - pydantic-settings==2.6.1
      - typing-inspect==0.9.0
      
      # Async support
      - greenlet==3.1.1
      - sse-starlette==2.0.0
      
      # gRPC and Protocol Buffers
      - protobuf==5.29.4
      - grpcio==1.71.0
      - grpcio-tools==1.71.0
      
      # Text processing
      - regex==2023.12.25
      - markupsafe==2.1.5
      - marshmallow==3.21.0
      - dataclasses-json==0.6.4
      - overrides==7.7.0
      - referencing==0.35.1
      - rpds-py==0.18.1
      - et-xmlfile==1.1.0
      - jinja2==3.1.4
      - jiter==0.8.2
      - mako==1.3.10
      - msgpack==1.1.0
      - cffi==1.17.1
      - pycparser==2.22
      - distro==1.9.0
      
      # Development tools
      - black==24.8.0
      - mypy==1.15.0
      - mypy-extensions==1.0.0
      - flake8==7.3.0
      - pycodestyle==2.14.0
      - pyflakes==3.4.0
      - mccabe==0.7.0
      - isort==6.0.1
      - pre-commit==4.2.0
      - pytest-asyncio==1.0.0
      - pytest-cov==6.2.1
      - coverage==7.9.1
      - nodeenv==1.9.1
      - cfgv==3.4.0
      - distlib==0.3.9
      - filelock==3.18.0
      - identify==2.6.12
      - virtualenv==20.31.2
      
      # Type stubs
      - pandas-stubs==2.2.1.240316
      - types-cffi==1.17.0.20250523
      - types-jsonschema==4.22.0.20240610
      - types-passlib==1.7.7.20250408
      - types-protobuf==6.30.2.20250516
      - types-pyasn1==0.6.0.20250208
      - types-pyopenssl==24.1.0.20240722
      - types-python-jose==3.4.0.20250224
      - types-pytz==2024.1.0.20240203
      - types-pyyaml==6.0.12.12
      - types-redis==4.6.0.20241004
      - types-requests==2.32.0.20240907
      - types-setuptools==80.8.0.20250521
      - types-urllib3==1.26.25.13

