#!/bin/bash
# Script to fix AWS server configuration to accept external connections

echo "======================================"
echo "Fix AWS Server Configuration"
echo "======================================"

echo ""
echo "This script will help fix the connection issues on your AWS EC2 server."
echo ""

echo "1. SSH into your EC2 server:"
echo "   ssh -i your-key.pem ec2-user@52.73.87.226"
echo ""

echo "2. Check if services are running:"
echo "   pm2 list"
echo ""

echo "3. Check what interfaces services are listening on:"
echo "   sudo netstat -tlnp | grep -E '8000|8100|8200'"
echo ""

echo "4. If services are listening on 127.0.0.1 or localhost only, you need to:"
echo ""
echo "   a. Update the FastAPI server configurations to listen on 0.0.0.0:"
echo ""
echo "   # Edit appservice_server_fastapi.py"
echo "   sudo nano ~/nirva/nirva_service/src/nirva_service/services/app_services/appservice_server_fastapi.py"
echo "   # Find: uvicorn.run(app, host=\"127.0.0.1\", port=8000)"
echo "   # Change to: uvicorn.run(app, host=\"0.0.0.0\", port=8000)"
echo ""
echo "   # Edit chat_server_fastapi.py"
echo "   sudo nano ~/nirva/nirva_service/src/nirva_service/services/langgraph_services/chat_server_fastapi.py"
echo "   # Change host to \"0.0.0.0\""
echo ""
echo "   # Edit analyzer_server_fastapi.py"
echo "   sudo nano ~/nirva/nirva_service/src/nirva_service/services/langgraph_services/analyzer_server_fastapi.py"
echo "   # Change host to \"0.0.0.0\""
echo ""
echo "   b. Restart the services:"
echo "   pm2 restart all"
echo ""

echo "5. Check AWS Security Group (in AWS Console):"
echo "   - Go to EC2 Dashboard"
echo "   - Find your instance"
echo "   - Click on Security tab"
echo "   - Click on the security group"
echo "   - Add inbound rules for:"
echo "     * Port 8000 (HTTP) from 0.0.0.0/0"
echo "     * Port 8100 (Custom TCP) from 0.0.0.0/0"
echo "     * Port 8200 (Custom TCP) from 0.0.0.0/0"
echo ""

echo "6. If you have a firewall on the EC2 instance, open the ports:"
echo "   sudo iptables -A INPUT -p tcp --dport 8000 -j ACCEPT"
echo "   sudo iptables -A INPUT -p tcp --dport 8100 -j ACCEPT"
echo "   sudo iptables -A INPUT -p tcp --dport 8200 -j ACCEPT"
echo "   sudo iptables-save"
echo ""

echo "7. Test from your local machine:"
echo "   curl http://52.73.87.226:8000/"
echo "   curl http://52.73.87.226:8000/url_config/v1/"
echo ""

echo "======================================"
echo "Common Issues:"
echo "======================================"
echo ""
echo "Issue: Services listening on localhost only"
echo "Solution: Change host from '127.0.0.1' or 'localhost' to '0.0.0.0' in server files"
echo ""
echo "Issue: Security group blocking ports"
echo "Solution: Add inbound rules in AWS Security Group for ports 8000, 8100, 8200"
echo ""
echo "Issue: Firewall on EC2 blocking ports"
echo "Solution: Use iptables commands above or disable firewall temporarily"
echo ""